services:
  postgres:
    image: postgres:18.1
    container_name: credit-payment-tool_postgres
    ports:
      - 35432:5432
    volumes:
      - ./infra/postgres/sql/:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USER: "cpt_admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - credit-payment-tool-network

volumes:
  postgres-data:
    external: false

networks:
  credit-payment-tool-network:
    driver: bridge
